version: '3.9'
services:
  # Сервис для разворачивания контейнера с базой данных
  postgres:
    container_name: postgres
    image: postgres:12
    hostname: database
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=intervals
      - POSTGRES_USER=intervals
      - POSTGRES_PASSWORD=229csx
    ports:
      - "5430:5432"
  # Сервис для разворачивания контейнера с приложением
  webapi:
    build:
      dockerfile: Dockerfile
      context: .
    hostname: webapi
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/intervals
      - POSTGRES_USER=intervals
      - POSTGRES_PASSWORD=229csx