server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:intervals
    username: admin
    password: 229csx
    driverClassName: org.h2.Driver
  thymeleaf:
    enabled=false:
  flyway:
    enabled: true
    locations:
      - db.migration
    validate:
      -on
      -migrate=false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect