server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/intervals
    username: intervals
    password: 229csx
  thymeleaf:
    enabled=false:
  flyway:
    enabled: true
    locations:
      - db.migration
    validate:
      -on
      -migrate=false
  jpa:
    hibernate:
      dialect-auto: update